<?php
/**
 * Dynamic Translation Dictionary (English & Bangla)
 */

$translations = [
    'en' => [
        // Navigation & Menu
        'nav_home' => 'Home',
        'nav_browse' => 'Browse Items',
        'nav_post' => 'Post Item',
        'nav_dashboard' => 'Dashboard',
        'nav_admin' => 'Admin Panel',
        'nav_logout' => 'Logout',
        'nav_profile' => 'Profile',
        'nav_notifications' => 'Notifications',
        'nav_my_reports' => 'My Reports',
        'nav_report_lost' => 'Report Lost',
        'nav_report_found' => 'Report Found',
        'nav_main_menu' => 'Main Menu',
        
        // Hero Section
        'hero_badge' => 'Over 1,000+ items reunited in Bangladesh',
        'hero_title' => 'Never Lose Hope of Finding Your',
        'hero_title_span' => 'Lost Items',
        'hero_subtitle' => 'The smart platform that connects lost items with their owners through intelligent matching, community support, and real-time notifications.',
        'btn_report_lost' => 'Report Lost Item',
        'btn_report_found' => 'Report Found Item',
        'check_free' => 'Free to use',
        'check_no_money' => 'No Money required',
        'stat_success_rate' => 'Success Rate',
        
        // Stats Section
        'stat_reunited' => 'Items Reunited',
        'stat_users' => 'Active Users',
        'stat_time' => 'Avg. Recovery Time',
        'stat_days' => '3 days',
        
        // How it works
        'how_title' => 'How It Works',
        'how_subtitle' => 'Our simple 4-step process helps reunite lost items with their owners quickly and efficiently.',
        'step1_title' => '1. Report an Item',
        'step1_desc' => 'Lost something? Report it with photos and details. Found something? Help return it to its owner.',
        'step2_title' => '2. Smart Matching',
        'step2_desc' => 'Our system automatically scans and matches your item with potential matches from our database.',
        'step3_title' => '3. Get Notified',
        'step3_desc' => 'Receive instant notifications when we find a potential match for your item.',
        'step4_title' => '4. Connect & Recover',
        'step4_desc' => 'Verify the item details and connect with the finder to arrange a safe meeting for recovery.',
        
        // Choose us
        'why_title' => 'Why Choose Lost & Found?',
        'why_subtitle' => 'Powerful features designed to make recovering your lost items easier than ever.',
        'feat1_title' => 'Report Lost Items',
        'feat1_desc' => 'Quickly report your lost items with photos and detailed descriptions to help others identify them.',
        'feat2_title' => 'Report Found Items',
        'feat2_desc' => 'Found something? Help return it to its owner by reporting it on our platform.',
        'feat3_title' => 'Smart Matching',
        'feat3_desc' => 'Our intelligent algorithm automatically matches lost and found items based on keywords and descriptions.',
        'feat4_title' => 'Real-time Notifications',
        'feat4_desc' => 'Get instant alerts when potential matches are found for your reported items.',
        'feat5_title' => 'Secure & Private',
        'feat5_desc' => 'Your personal information is protected. Only share what you\'re comfortable with.',
        'feat6_title' => 'Community Driven',
        'feat6_desc' => 'Join a community of helpful people working together to reunite lost items with their owners.',
        
        // Dynamic Dash/General
        'welcome' => 'Welcome back',
        'dash_subtitle' => 'Here\'s what\'s happening with your Lost & Found activity',
        'total_lost' => 'Lost Items',
        'total_lost_desc' => 'Items reported lost',
        'total_found' => 'Found Items',
        'total_found_desc' => 'Items reported found',
        'total_matched' => 'Matched',
        'total_matched_desc' => 'Successful matches',
        'community' => 'Community',
        'community_desc' => 'Total platform users',
        'quick_actions' => 'Quick Actions',
        'recent_notifications' => 'Recent Notifications',
        'all_caught_up' => 'All caught up!',
        'no_new_notif' => 'No new notifications at the moment',
        'recent_activity' => 'Recent Activity',
        'no_recent_act' => 'No recent activity',
        'start_by_reporting' => 'Start by reporting a lost or found item above',
        'report_item' => 'Report an Item',
        
        // Auth
        'welcome_back_title' => 'Welcome Back',
        'login_subtitle' => 'Login to access the item recovery system',
        'email' => 'Email',
        'password' => 'Password',
        'login' => 'Login',
        'no_account' => 'Don\'t have an account?',
        'register_here' => 'Register here',
        'create_account' => 'Create Account',
        'register_subtitle' => 'Register to start using Lost & Found Portal',
        'username' => 'Username',
        'confirm_password' => 'Confirm Password',
        'register' => 'Register',
        'have_account' => 'Already have an account?',
        'login_here' => 'Login here',
        // Story & CTA Section
        'story1_title' => 'Every Item Tells a Story',
        'story1_desc' => 'From phones and wallets to keys and jewelry, we understand that every lost item has sentimental value. Our platform is designed to give you the best chance of recovery by leveraging community support and smart technology.',
        'story1_li1' => 'Upload photos and detailed descriptions',
        'story1_li2' => 'Browse found items by category and location',
        'story1_li3' => 'Receive instant match notifications',
        'story2_title' => 'Powered by Smart Technology',
        'story2_desc' => 'Our intelligent matching algorithm analyzes keywords, descriptions, locations, and categories to automatically find potential matches. The more details you provide, the better the matching results!',
        'story2_li1' => 'AI-powered keyword matching',
        'story2_li2' => 'Location-based smart filtering',
        'story2_li3' => 'Real-time database synchronisation',
        'cta_title' => 'Ready to Find Your Lost Items?',
        'cta_desc' => 'Join thousands of users who have successfully recovered their belongings through our platform.',
        'cta_btn1' => 'Get Started Now',
        'cta_btn2' => 'Browse Items',
        
        // Browse Page
        'browse_title' => 'Browse Items',
        'browse_subtitle' => 'Explore all reported items in the community',
        'search_keyword' => 'Search Keyword',
        'search_placeholder' => 'What are you looking for?',
        'all_categories' => 'All Categories',
        'cat_electronics' => 'Electronics',
        'cat_personal_effects' => 'Personal Effects',
        'cat_documents' => 'Documents',
        'cat_stationery' => 'Stationery',
        'cat_other' => 'Other',
        'all_types' => 'All Types',
        'type_lost' => 'Lost',
        'type_found' => 'Found',
        'view_details' => 'View Details',
        'no_items_found' => 'No items found matching your criteria.',
        'clear_filters' => 'Clear filters',

        // My Reports
        'my_reports_title' => 'My Reports',
        'my_reports_subtitle' => 'Manage your lost and found item reports',
        'lost_items_count' => 'Lost Items (%d)',
        'found_items_count' => 'Found Items (%d)',
        'edit' => 'Edit',
        'no_reports_reported' => 'No %s items reported',
        'start_by_reporting_type' => 'Start by reporting a lost or found item',
        'report_type_item' => 'Report a %s Item',

        // Post Item
        'report_item_title' => 'Report Item',
        'report_item_subtitle' => 'Help us reunite lost items with their owners',
        'item_type' => 'Item Type',
        'i_lost_something' => 'I Lost Something',
        'i_found_something' => 'I Found Something',
        'item_title' => 'Item Title',
        'item_title_placeholder' => 'e.g. Blue Wallet, iPhone 13',
        'location' => 'Location',
        'location_placeholder' => 'e.g. UIU Cafeteria, Room 402',
        'date' => 'Date',
        'image_optional' => 'Image (Optional)',
        'keywords_label' => 'Keywords (For Smart Matching)',
        'keywords_placeholder' => 'e.g. blue leather wallet cash cards',
        'keywords_help' => 'Separate words with spaces. More keywords = better matches!',
        'description' => 'Description',
        'description_placeholder' => 'Describe the item in detail...',
        'btn_post_report' => 'Post Item Report',

        // Notifications
        'notif_title' => 'Notifications',
        'notif_subtitle' => 'Stay updated on your item matches and claims',
        'notif_empty_title' => "You're all caught up!",
        'notif_empty_desc' => "You'll be notified here when there's activity on your reports — such as a potential match or a claim request from someone.",

        // Profile
        'profile_title' => 'My Profile',
        'profile_subtitle' => 'Manage your account settings and preferences',
        'personal_info' => 'Personal Information',
        'edit_profile' => 'Edit Profile',
        'save_changes' => 'Save Changes',
        'cancel' => 'Cancel',
        'username' => 'Username',
        'email_address' => 'Email Address',
        'role' => 'Role',
        'member_since' => 'Member Since',
        'security' => 'Security',
        'security_desc' => 'Manage your password and account security settings.',
        'change_password' => 'Change Password',
        'account_stats' => 'Account Stats',
        'resolved' => 'Resolved',
        'account_status' => 'Account Status',
        'email_verified' => 'Email verified',
        'account_secured' => 'Account secured',
        'profile_complete' => 'Profile complete',

        // Item Details
        'back' => 'Back',
        'posted_success' => 'Item posted successfully!',
        'claim_submitted_success' => 'Claim submitted successfully! The item owner will be notified.',
        'reported_by' => 'Reported by',
        'is_this_yours' => 'Is this yours?',
        'did_you_find_this' => 'Did you find this?',
        'thats_mine' => "That's Mine!",
        'i_found_this' => 'I Found This!',
        'your_item' => 'Your Item',
        'your_item_desc' => 'This is an item you reported. Check your dashboard for claim updates.',
        'share' => 'Share',
        'copy_link' => 'Copy Link',
        'claim_item' => 'Claim this item',
        'claim_item_desc' => 'Tell us why this item belongs to you',
        'message' => 'Message',
        'message_placeholder' => 'Describe why this is your item, provide any identifying details...',
        'submit_claim' => 'Submit Claim',
        'claim_requests' => 'Claim Requests (%d)',
        'claim_requests_desc' => 'Review the claims submitted by other users for this item.',
        'claim_from' => 'Claim from: ',
        'claim_proof' => 'Claim Message / Proof',
        'submitted' => 'Submitted',
        'accept' => 'Accept',
        'reject' => 'Reject',
        'no_claims_yet' => 'No claim requests have been submitted for this item yet.',
        'potential_matches' => 'Potential Matches',
        'potential_matches_desc' => "Our algorithm found these items that might be what you're looking for!",
        'keyword_matches' => '%d Keyword Matches',
        'matched_keywords' => 'Matched: %s',
        'check_it_out' => 'Check it out',
        'login_to_claim' => 'Login to Claim',
        'copied' => 'Copied!',
        'view_all' => 'View All',
        'quick_lost_desc' => 'Something missing? Tell us about it',
        'quick_found_desc' => 'Help someone get it back',
        'quick_browse_desc' => 'Search available items',
        'quick_my_reports_desc' => 'Manage your submissions',
        'status' => 'Status',
        'category' => 'Category',
        'location' => 'Location',
        'date' => 'Date',
        'open' => 'Open',
        'pending' => 'Pending',
        'update_security_creds' => 'Update your account security credentials',
        'security_settings' => 'Security Settings',
        'choose_strong_password' => 'Choose a strong password to keep your account safe',
        'current_password' => 'Current Password',
        'new_password' => 'New Password',
        'confirm_new_password' => 'Confirm New Password',
        'update_password' => 'Update Password',
        'enter_current_pw' => 'Enter your current password',
        'min_characters' => 'Minimum 8 characters',
        'reenter_new_pw' => 'Re-enter new password',
        'weak' => 'Weak',
        'fair' => 'Fair',
        'good' => 'Good',
        'strong' => 'Strong',
        'match_ok' => '✓ Passwords match',
        'match_err' => '✗ Passwords do not match',
        'back_to_reports' => 'Back to My Reports',
        'edit_item' => 'Edit Item',
        'edit_item_desc' => 'Update the details of your reported item',
        'type_fixed_help' => 'Type cannot be changed after posting',
        'date_spotted' => 'Date Spotted',
        'current_image' => 'Current Image',
        'replace_image' => 'Replace Image (Optional)',
        'no_image_uploaded' => 'No image uploaded',
        'keywords_help_edit' => 'Separate with spaces for better matching',
        
        // --- Added Translation Keys ---
        'verification_blur' => 'Verification Blur',
        'blur_desc_protected' => 'Protected preview to prevent false claims',
        'claim_item_title' => 'Claim Item',
        'claiming_desc' => 'You are claiming:',
        'posted_by' => 'Posted by:',
        'found_at' => 'Found at:',
        'proof_ownership_msg' => 'Proof of Ownership / Message',
        'verification_blur_protected' => 'Verification Blur Protected',
        'blur_desc_owner' => 'The owner has blurred this picture to protect privacy. Submit a claim below to view the clean image once approved.',
        'proof_image_optional' => 'Proof Image (Optional but Recommended)',
        'keywords_comma_separated' => 'Keywords (comma separated)',
        'blur_desc_login' => 'Login or create an account to submit a claim and see the unblurred image once approved.',
        'registration_successful' => 'Registration successful! Please login.',
        'footer_desc' => 'Connecting people with their lost belongings through intelligent matching, community support, and real-time notifications.',
        'platform' => 'Platform',
        'company' => 'Company',
        'contact_us' => 'Contact Us',
        'about_us' => 'About Us',
        'contact' => 'Contact',
        'privacy_policy' => 'Privacy Policy',
        'terms_of_service' => 'Terms of Service',
        'privacy' => 'Privacy',
        'terms' => 'Terms',
        'cookies' => 'Cookies',
        'member' => 'Member',
        'dashboard_title' => 'Dashboard - Lost & Found',
        'login_title' => 'Login | Lost & Found',
        'register_title' => 'Signup | Lost & Found',
        'home_title' => 'Lost & Found | Find What You Lost',
        
        // Admin
        'admin_panel_title' => 'Admin Panel',
        'admin_panel_desc' => 'Manage users, items, claims, and system settings',
        'total_users' => 'Total Users',
        'total_items' => 'Total Items',
        'total_claims' => 'Total Claims',
        'system_matches' => 'System Matches',
        'pending_verification' => 'Pending Verification',
        'success_rate' => 'Success Rate',
        'item_type_dist' => 'Item Type Distribution',
        'item_status_dist' => 'Item Status Distribution',
        'claim_status_dist' => 'Claim Status',
        'category_dist' => 'Category Distribution',
        'recent_activity' => 'Recent Activity',
        
        'manage_users' => 'Manage Users',
        'manage_users_desc' => 'View and manage all registered users',
        'all_users' => 'All Users',
        'joined_on' => 'Joined on:',
        
        'manage_items' => 'Manage Items',
        'manage_items_desc' => 'View and manage all reported items',
        'all_items' => 'All Items',
        
        'manage_claims' => 'Manage Claims',
        'manage_claims_desc' => 'Review and process all item claim requests',
        'all_statuses' => 'All Statuses',
        'accepted' => 'Accepted',
        'rejected' => 'Rejected',
        'all_claims' => 'All Claims',
        'claimed_by' => 'Claimed By',
        'item_owner' => 'Item Owner',
        
        'verify_matches' => 'Verify System Matches',
        'verify_matches_desc' => 'Review and verify high-confidence matches generated by the Smart Algorithm',
        'match_heuristics' => 'Match Heuristics:',
        'no_pending_matches' => 'There are no pending system matches to verify.',
        
        'admin_security' => 'Admin Security',
        'admin_security_desc' => 'Use a strong, unique password for your admin account',
    ],
    'bn' => [
        // Navigation & Menu
        'nav_home' => 'হোম',
        'nav_browse' => 'জিনিসপত্র খুঁজুন',
        'nav_post' => 'পোস্ট করুন',
        'nav_dashboard' => 'ড্যাশবোর্ড',
        'nav_admin' => 'অ্যাডমিন প্যানেল',
        'nav_logout' => 'লগআউট',
        'nav_profile' => 'প্রোফাইল',
        'nav_notifications' => 'নোটিফিকেশন',
        'nav_my_reports' => 'আমার রিপোর্টসমূহ',
        'nav_report_lost' => 'হারানো রিপোর্ট',
        'nav_report_found' => 'পাওয়া রিপোর্ট',
        'nav_main_menu' => 'প্রধান মেনু',
        
        // Hero Section
        'hero_badge' => 'বাংলাদেশে ১,০০০+ এর বেশি জিনিসপত্র ফেরত দেওয়া হয়েছে',
        'hero_title' => 'আপনার হারানো জিনিস খুঁজে পাওয়ার আশা',
        'hero_title_span' => 'কখনো হারাবেন না',
        'hero_subtitle' => 'হারানো ও পাওয়া জিনিসপত্রের মালিকদের বুদ্ধিমান ম্যাচিং, কমিউনিটি সহায়তা এবং রিয়েল-টাইম নোটিফিকেশনের মাধ্যমে সরাসরি সংযোগ স্থাপন করার একটি স্মার্ট প্ল্যাটফর্ম।',
        'btn_report_lost' => 'হারানো জিনিস পোস্ট করুন',
        'btn_report_found' => 'পাওয়া জিনিস পোস্ট করুন',
        'check_free' => 'ব্যবহার করা সম্পূর্ণ ফ্রি',
        'check_no_money' => 'কোনো টাকা লাগবে না',
        'stat_success_rate' => 'সাফল্যের হার',
        
        // Stats Section
        'stat_reunited' => 'জিনিসপত্র ফেরত দেওয়া হয়েছে',
        'stat_users' => 'সক্রিয় ব্যবহারকারী',
        'stat_time' => 'গড় পুনরুদ্ধারের সময়',
        'stat_days' => '৩ দিন',
        
        // How it works
        'how_title' => 'এটি কীভাবে কাজ করে',
        'how_subtitle' => 'আমাদের ৪-ধাপের প্রক্রিয়া খুব দ্রুত এবং দক্ষতার সাথে মালিকদের সাথে সংযোগ স্থাপন করে।',
        'step1_title' => '১. রিপোর্ট করুন',
        'step1_desc' => 'কিছু হারিয়েছেন? ছবি ও বিবরণ দিয়ে পোস্ট করুন। কিছু পেয়েছেন? সেটি ফেরত দিতে সাহায্য করুন।',
        'step2_title' => '২. স্মার্ট ম্যাচিং',
        'step2_desc' => 'আমাদের স্মার্ট অ্যালগরিদম স্বয়ংক্রিয়ভাবে আপনার জিনিসপত্রের সাথে অন্যান্য জিনিস স্ক্যান ও ম্যাচ করে।',
        'step3_title' => '৩. নোটিফিকেশন পান',
        'step3_desc' => 'যখনই কোনো সম্ভাব্য ম্যাচ পাওয়া যাবে, সাথে সাথে আপনি ইমেইল বা নোটিফিকেশন পাবেন।',
        'step4_title' => '৪. যোগাযোগ ও পুনরুদ্ধার',
        'step4_desc' => 'জিনিসপত্রের সত্যতা যাচাই করুন এবং নিরাপদে একে অপরের সাথে দেখা করে জিনিসটি পুনরুদ্ধার করুন।',
        
        // Choose us
        'why_title' => 'কেন আমাদের প্ল্যাটফর্ম বেছে নেবেন?',
        'why_subtitle' => 'আপনার হারানো জিনিস পুনরুদ্ধার করা সহজ করার জন্য শক্তিশালী ও আধুনিক সব ফিচার।',
        'feat1_title' => 'হারানো জিনিসের রিপোর্ট',
        'feat1_desc' => 'ছবি এবং বিস্তারিত বিবরণ দিয়ে খুব সহজেই আপনার হারানো জিনিসটি পোস্ট করুন যেন অন্যরা চিনতে পারে।',
        'feat2_title' => 'পাওয়া জিনিসের রিপোর্ট',
        'feat2_desc' => 'রাস্তায় বা কোথাও কোনো জিনিস কুড়িয়ে পেয়েছেন? আমাদের এখানে পোস্ট করে আসল মালিকের কাছে ফেরত দিন।',
        'feat3_title' => 'স্মার্ট ম্যাচিং',
        'feat3_desc' => 'আমাদের বুদ্ধিমান সিস্টেম কি-ওয়ার্ড এবং বিবরণের ওপর ভিত্তি করে স্বয়ংক্রিয়ভাবে হারানো ও পাওয়া জিনিস মিলিয়ে দেয়।',
        'feat4_title' => 'রিয়েল-টাইম নোটিফিকেশন',
        'feat4_desc' => 'আপনার কুড়িয়ে পাওয়া বা হারিয়ে যাওয়া জিনিসপত্রের যেকোনো সম্ভাব্য ম্যাচ এলেই সাথে সাথে অ্যালার্ট পান।',
        'feat5_title' => 'নিরাপদ ও ব্যক্তিগত',
        'feat5_desc' => 'আপনার ব্যক্তিগত তথ্য সম্পূর্ণ সুরক্ষিত। আপনি যতটুকু স্বাচ্ছন্দ্য বোধ করেন ততটুকুই শেয়ার করুন।',
        'feat6_title' => 'কমিউনিটি চালিত',
        'feat6_desc' => 'সহায়তা করতে প্রস্তুত এমন এক বিশাল সম্প্রদায়ের সাথে যোগ দিন যারা জিনিসপত্র ফিরিয়ে দিতে কাজ করে।',
        
        // Dynamic Dash/General
        'welcome' => 'স্বাগতম',
        'dash_subtitle' => 'আপনার ড্যাশবোর্ড এবং হারানো-পাওয়া জিনিসপত্রের কার্যকলাপের সর্বশেষ বিবরণ',
        'total_lost' => 'হারানো জিনিসপত্র',
        'total_lost_desc' => 'যেসব জিনিসের রিপোর্ট করা হয়েছে',
        'total_found' => 'পাওয়া জিনিসপত্র',
        'total_found_desc' => 'কুড়িয়ে পাওয়া জিনিসের তালিকা',
        'total_matched' => 'ফিরে পেয়েছেন',
        'total_matched_desc' => 'সফলভাবে মিলিয়ে দেওয়া হয়েছে',
        'community' => 'কমিউনিটি',
        'community_desc' => 'মোট সক্রিয় ব্যবহারকারী',
        'quick_actions' => 'দ্রুত অ্যাকশন',
        'recent_notifications' => 'সাম্প্রতিক নোটিফিকেশন',
        'all_caught_up' => 'সব নোটিফিকেশন দেখা শেষ!',
        'no_new_notif' => 'এই মুহূর্তে কোনো নতুন নোটিফিকেশন নেই',
        'recent_activity' => 'সাম্প্রতিক কার্যকলাপ',
        'no_recent_act' => 'কোনো সাম্প্রতিক কার্যকলাপ পাওয়া যায়নি',
        'start_by_reporting' => 'উপরে ক্লিক করে একটি হারানো বা পাওয়া জিনিসের রিপোর্ট করুন',
        'report_item' => 'রিপোর্ট পোস্ট করুন',
        
        // Auth
        'welcome_back_title' => 'আবারও স্বাগতম',
        'login_subtitle' => 'হারানো জিনিস পুনরুদ্ধার সিস্টেমে প্রবেশ করতে লগইন করুন',
        'email' => 'ইমেইল অ্যাড্রেস',
        'password' => 'পাসওয়ার্ড',
        'login' => 'লগইন করুন',
        'no_account' => 'নতুন অ্যাকাউন্ট তৈরি করতে চান?',
        'register_here' => 'এখানে রেজিস্টার করুন',
        'create_account' => 'অ্যাকাউন্ট তৈরি করুন',
        'register_subtitle' => 'পোর্টালটি ব্যবহার করতে নতুন অ্যাকাউন্ট নিবন্ধন করুন',
        'username' => 'ব্যবহারকারীর নাম',
        'confirm_password' => 'পাসওয়ার্ড নিশ্চিত করুন',
        'register' => 'নিবন্ধন করুন',
        'have_account' => 'ইতিমধ্যে অ্যাকাউন্ট আছে?',
        'login_here' => 'এখানে লগইন করুন',
        // Story & CTA Section
        'story1_title' => 'প্রত্যেকটি জিনিসের একটি গল্প থাকে',
        'story1_desc' => 'মোবাইল ও ওয়ালেট থেকে শুরু করে চাবি এবং গহনা পর্যন্ত, আমরা বুঝি যে প্রতিটি হারানো জিনিসের একটি বিশেষ আবেগগত মূল্য রয়েছে। আমাদের প্ল্যাটফর্মটি তৈরি করা হয়েছে যেন উন্নত প্রযুক্তি এবং কমিউনিটির সহায়তায় আপনি সহজে জিনিসটি ফেরত পান।',
        'story1_li1' => 'ছবি এবং বিস্তারিত বিবরণ দিয়ে রিপোর্ট করুন',
        'story1_li2' => 'শ্রেণীবিভাগ এবং অবস্থান অনুযায়ী জিনিস খুঁজুন',
        'story1_li3' => 'স্বয়ংক্রিয়ভাবে ম্যাচের নোটিফিকেশন পান',
        'story2_title' => 'স্মার্ট প্রযুক্তি দ্বারা চালিত',
        'story2_desc' => 'আমাদের বুদ্ধিমান ম্যাচিং অ্যালগরিদম কি-ওয়ার্ড, বিবরণ এবং অবস্থান বিশ্লেষণ করে স্বয়ংক্রিয়ভাবে আপনার জন্য সম্ভাব্য ম্যাচিং খুঁজে বের করে। যত বেশি তথ্য দিবেন, ম্যাচিং তত ভালো হবে!',
        'story2_li1' => 'এআই-চালিত কি-ওয়ার্ড ম্যাচিং প্রযুক্তি',
        'story2_li2' => 'অবস্থান-ভিত্তিক আকর্ষণীয় ফিল্টারিং',
        'story2_li3' => 'রিয়েল-টাইম সমন্বয় ব্যবস্থা',
        'cta_title' => 'আপনার হারানো জিনিস খুঁজে পেতে প্রস্তুত?',
        'cta_desc' => 'আমাদের পোর্টালের মাধ্যমে সফলভাবে জিনিসপত্র উদ্ধারকারী হাজার হাজার সন্তুষ্ট ব্যবহারকারীদের সাথে যোগ দিন।',
        'cta_btn1' => 'এখনই শুরু করুন',
        'cta_btn2' => 'জিনিসপত্র দেখুন',
        
        // Browse Page
        'browse_title' => 'জিনিসপত্র খুঁজুন',
        'browse_subtitle' => 'আমাদের সম্প্রদায়ে রিপোর্ট করা সমস্ত জিনিসপত্র দেখুন',
        'search_keyword' => 'কি-ওয়ার্ড দিয়ে খুঁজুন',
        'search_placeholder' => 'আপনি কী খুঁজছেন?',
        'all_categories' => 'সব ক্যাটাগরি',
        'cat_electronics' => 'ইলেকট্রনিক্স',
        'cat_personal_effects' => 'ব্যক্তিগত জিনিসপত্র',
        'cat_documents' => 'নথিপত্র',
        'cat_stationery' => 'স্টেশনারি',
        'cat_other' => 'অন্যান্য',
        'all_types' => 'সব ধরন',
        'type_lost' => 'হারানো',
        'type_found' => 'পাওয়া',
        'view_details' => 'বিস্তারিত দেখুন',
        'no_items_found' => 'আপনার সার্চের সাথে মেলে এমন কোনো জিনিস পাওয়া যায়নি।',
        'clear_filters' => 'ফিল্টার মুছুন',

        // My Reports
        'my_reports_title' => 'আমার রিপোর্টসমূহ',
        'my_reports_subtitle' => 'আপনার হারানো ও পাওয়া জিনিসের রিপোর্ট পরিচালনা করুন',
        'lost_items_count' => 'হারানো জিনিসপত্র (%d)',
        'found_items_count' => 'পাওয়া জিনিসপত্র (%d)',
        'edit' => 'সম্পাদনা',
        'no_reports_reported' => 'কোনো %s জিনিসের রিপোর্ট করা হয়নি',
        'start_by_reporting_type' => 'একটি হারানো বা পাওয়া জিনিস রিপোর্ট করার মাধ্যমে শুরু করুন',
        'report_type_item' => 'একটি %s জিনিস রিপোর্ট করুন',

        // Post Item
        'report_item_title' => 'রিপোর্ট পোস্ট করুন',
        'report_item_subtitle' => 'হারানো জিনিস আসল মালিকের কাছে ফিরিয়ে দিতে সাহায্য করুন',
        'item_type' => 'জিনিসের ধরন',
        'i_lost_something' => 'আমার কোনো জিনিস হারিয়েছে',
        'i_found_something' => 'আমি কোনো জিনিস পেয়েছি',
        'item_title' => 'জিনিসের শিরোনাম',
        'item_title_placeholder' => 'যেমন: নীল রঙের মানিব্যাগ, আইফোন ১৩',
        'location' => 'স্থান / লোকেশন',
        'location_placeholder' => 'যেমন: ইউআইইউ ক্যাফেটেরিয়া, রুম ৪০২',
        'date' => 'তারিখ',
        'image_optional' => 'ছবি (ঐচ্ছিক)',
        'keywords_label' => 'কি-ওয়ার্ড (স্মার্ট ম্যাচিংয়ের জন্য)',
        'keywords_placeholder' => 'যেমন: নীল চামড়ার মানিব্যাগ টাকা কার্ড',
        'keywords_help' => 'শব্দগুলো স্পেস দিয়ে আলাদা করুন। বেশি কি-ওয়ার্ড দিলে ভালো ম্যাচিং হবে!',
        'description' => 'বিস্তারিত বিবরণ',
        'description_placeholder' => 'জিনিসটি সম্পর্কে বিস্তারিত বর্ণনা লিখুন...',
        'btn_post_report' => 'রিপোর্ট পোস্ট করুন',

        // Notifications
        'notif_title' => 'নোটিফিকেশন',
        'notif_subtitle' => 'হারানো জিনিসের ম্যাচ ও দাবিসমূহ সম্পর্কে আপ-টু-ডেট থাকুন',
        'notif_empty_title' => 'সব নোটিফিকেশন দেখা শেষ!',
        'notif_empty_desc' => 'আপনার রিপোর্টে যেকোনো কার্যকলাপ (যেমন সম্ভাব্য ম্যাচ অথবা কারো দাবির অনুরোধ) হলে আপনাকে এখানে জানানো হবে।',

        // Profile
        'profile_title' => 'আমার প্রোফাইল',
        'profile_subtitle' => 'আপনার অ্যাকাউন্টের সেটিংস এবং পছন্দসমূহ পরিচালনা করুন',
        'personal_info' => 'ব্যক্তিগত তথ্য',
        'edit_profile' => 'প্রোফাইল সম্পাদনা',
        'save_changes' => 'পরিবর্তন সংরক্ষণ করুন',
        'cancel' => 'বাতিল',
        'username' => 'ব্যবহারকারীর নাম',
        'email_address' => 'ইমেইল অ্যাড্রেস',
        'role' => 'ভূমিকা',
        'member_since' => 'নিবন্ধনের তারিখ',
        'security' => 'নিরাপত্তা',
        'security_desc' => 'আপনার পাসওয়ার্ড এবং অ্যাকাউন্ট নিরাপত্তা সেটিংস পরিচালনা করুন।',
        'change_password' => 'পাসওয়ার্ড পরিবর্তন করুন',
        'account_stats' => 'অ্যাকাউন্ট পরিসংখ্যান',
        'resolved' => 'সমাধানকৃত',
        'account_status' => 'অ্যাকাউন্ট স্ট্যাটাস',
        'email_verified' => 'ইমেইল যাচাইকৃত',
        'account_secured' => 'অ্যাকাউন্ট সুরক্ষিত',
        'profile_complete' => 'প্রোফাইল সম্পূর্ণ',

        // Item Details
        'back' => 'পেছনে যান',
        'posted_success' => 'জিনিসটি সফলভাবে পোস্ট করা হয়েছে!',
        'claim_submitted_success' => 'দাবি সফলভাবে জমা দেওয়া হয়েছে! জিনিসের মালিককে অবহিত করা হবে।',
        'reported_by' => 'রিপোর্ট করেছেন',
        'is_this_yours' => 'এটি কি আপনার?',
        'did_you_find_this' => 'আপনি কি এটি পেয়েছেন?',
        'thats_mine' => 'এটি আমার!',
        'i_found_this' => 'আমি এটি পেয়েছি!',
        'your_item' => 'আপনার পোস্টকৃত জিনিস',
        'your_item_desc' => 'এটি আপনার রিপোর্ট করা একটি জিনিস। আপডেটের জন্য আপনার ড্যাশবোর্ড দেখুন।',
        'share' => 'শেয়ার করুন',
        'copy_link' => 'লিংক কপি করুন',
        'claim_item' => 'জিনিসটি দাবি করুন',
        'claim_item_desc' => 'জিনিসটি কেন আপনার তা আমাদের বলুন',
        'message' => 'বার্তা / বিবরণ',
        'message_placeholder' => 'এটি কেন আপনার জিনিস তা বর্ণনা করুন এবং কোনো সনাক্তকারী বিবরণ থাকলে তা প্রদান করুন...',
        'submit_claim' => 'দাবি পেশ করুন',
        'claim_requests' => 'দাবির অনুরোধসমূহ (%d)',
        'claim_requests_desc' => 'এই জিনিসের জন্য অন্যান্য ব্যবহারকারীদের জমা দেওয়া দাবিগুলো পর্যালোচনা করুন।',
        'claim_from' => 'দাবি করেছেন: ',
        'claim_proof' => 'দাবির বার্তা / প্রমাণ',
        'submitted' => 'জমা দেওয়া হয়েছে',
        'accept' => 'অনুমোদন করুন',
        'reject' => 'প্রত্যাখ্যান করুন',
        'no_claims_yet' => 'এই জিনিসের জন্য এখনো কোনো দাবির অনুরোধ জমা দেওয়া হয়নি।',
        'potential_matches' => 'সম্ভাব্য ম্যাচসমূহ',
        'potential_matches_desc' => 'আমাদের অ্যালগরিদম এমন কিছু জিনিস খুঁজে পেয়েছে যা আপনার হারানো জিনিসের সাথে মিলে যেতে পারে!',
        'keyword_matches' => '%d টি কি-ওয়ার্ড মিলেছে',
        'matched_keywords' => 'মিলেছে: %s',
        'check_it_out' => 'এক নজর দেখুন',
        'login_to_claim' => 'দাবি করতে লগইন করুন',
        'copied' => 'কপি হয়েছে!',
        'view_all' => 'সব দেখুন',
        'quick_lost_desc' => 'কোনো কিছু হারিয়েছেন? আমাদের জানান',
        'quick_found_desc' => 'কাউকে তার জিনিসটি ফেরত পেতে সাহায্য করুন',
        'quick_browse_desc' => 'হারানো বা পাওয়া জিনিসপত্র খুঁজুন',
        'quick_my_reports_desc' => 'আপনার রিপোর্টসমূহ পরিচালনা করুন',
        'status' => 'স্ট্যাটাস / অবস্থা',
        'category' => 'শ্রেণী / ক্যাটাগরি',
        'location' => 'স্থান / লোকেশন',
        'date' => 'তারিখ',
        'open' => 'চলতি',
        'pending' => 'অপেক্ষমান',
        'update_security_creds' => 'আপনার অ্যাকাউন্টের নিরাপত্তা পাসওয়ার্ড আপডেট করুন',
        'security_settings' => 'নিরাপত্তা সেটিংস',
        'choose_strong_password' => 'আপনার অ্যাকাউন্ট সুরক্ষিত রাখতে একটি শক্তিশালী পাসওয়ার্ড চয়ন করুন',
        'current_password' => 'বর্তমান পাসওয়ার্ড',
        'new_password' => 'নতুন পাসওয়ার্ড',
        'confirm_new_password' => 'নতুন পাসওয়ার্ড নিশ্চিত করুন',
        'update_password' => 'পাসওয়ার্ড আপডেট করুন',
        'enter_current_pw' => 'আপনার বর্তমান পাসওয়ার্ড লিখুন',
        'min_characters' => 'সর্বনিম্ন ৮ টি অক্ষর',
        'reenter_new_pw' => 'নতুন পাসওয়ার্ডটি আবার লিখুন',
        'weak' => 'দুর্বল',
        'fair' => 'মোটামুটি',
        'good' => 'ভালো',
        'strong' => 'শক্তিশালী',
        'match_ok' => '✓ পাসওয়ার্ড দুটি মিলেছে',
        'match_err' => '✗ পাসওয়ার্ড দুটি মেলেনি',
        'back_to_reports' => 'আমার রিপোর্টে ফিরে যান',
        'edit_item' => 'রিপোর্ট সম্পাদনা করুন',
        'edit_item_desc' => 'আপনার পোস্টকৃত রিপোর্টের বিবরণ আপডেট করুন',
        'type_fixed_help' => 'রিপোর্ট পোস্ট করার পর ধরন পরিবর্তন করা যাবে না',
        'date_spotted' => 'তারিখ',
        'current_image' => 'বর্তমান ছবি',
        'replace_image' => 'ছবি পরিবর্তন করুন (ঐচ্ছিক)',
        'no_image_uploaded' => 'কোনো ছবি আপলোড করা হয়নি',
        'keywords_help_edit' => 'স্মার্ট ম্যাচিংয়ের জন্য শব্দগুলো স্পেস দিয়ে আলাদা করুন',
        
        // --- Added Translation Keys ---
        'verification_blur' => 'যাচাইকরণ অস্পষ্টতা',
        'blur_desc_protected' => 'মিথ্যা দাবি রোধ করতে সুরক্ষিত প্রিভিউ',
        'claim_item_title' => 'জিনিস দাবি করুন',
        'claiming_desc' => 'আপনি দাবি করছেন:',
        'posted_by' => 'পোস্ট করেছেন:',
        'found_at' => 'পাওয়া গেছে:',
        'proof_ownership_msg' => 'মালিকানার প্রমাণ / বার্তা',
        'verification_blur_protected' => 'যাচাইকরণের জন্য ছবি সুরক্ষিত',
        'blur_desc_owner' => 'গোপনীয়তা রক্ষার জন্য মালিক এই ছবিটি ঝাপসা করেছেন। অনুমোদনের পর পরিষ্কার ছবি দেখতে নিচে একটি দাবি পেশ করুন।',
        'proof_image_optional' => 'প্রমাণ ছবি (ঐচ্ছিক তবে প্রস্তাবিত)',
        'keywords_comma_separated' => 'কি-ওয়ার্ড (কমা দিয়ে আলাদা করা)',
        'blur_desc_login' => 'একটি দাবি পেশ করতে এবং অনুমোদনের পর পরিষ্কার ছবি দেখতে লগইন করুন বা অ্যাকাউন্ট তৈরি করুন।',
        'registration_successful' => 'নিবন্ধন সফল হয়েছে! অনুগ্রহ করে লগইন করুন।',
        'footer_desc' => 'স্মার্ট ম্যাচিং, কমিউনিটির সহায়তা এবং তাৎক্ষণিক নোটিফিকেশনের মাধ্যমে মানুষের সাথে তাদের হারানো জিনিসপত্রের সংযোগ স্থাপন।',
        'platform' => 'প্ল্যাটফর্ম',
        'company' => 'কোম্পানি',
        'contact_us' => 'যোগাযোগ',
        'about_us' => 'আমাদের সম্পর্কে',
        'contact' => 'যোগাযোগ',
        'privacy_policy' => 'গোপনীয়তা নীতি',
        'terms_of_service' => 'সেবার শর্তাবলী',
        'privacy' => 'গোপনীয়তা',
        'terms' => 'শর্তাবলী',
        'cookies' => 'কুকিজ',
        'member' => 'সদস্য',
        'dashboard_title' => 'ড্যাশবোর্ড - লস্ট অ্যান্ড ফাউন্ড',
        'login_title' => 'লগইন | লস্ট অ্যান্ড ফাউন্ড',
        'register_title' => 'নিবন্ধন | লস্ট অ্যান্ড ফাউন্ড',
        'home_title' => 'লস্ট অ্যান্ড ফাউন্ড | আপনার হারানো জিনিস খুঁজুন',
        
        // Admin
        'admin_panel_title' => 'অ্যাডমিন প্যানেল',
        'admin_panel_desc' => 'ব্যবহারকারী, জিনিসপত্র, দাবি এবং সিস্টেম সেটিংস পরিচালনা করুন',
        'total_users' => 'মোট ব্যবহারকারী',
        'total_items' => 'মোট জিনিসপত্র',
        'total_claims' => 'মোট দাবি',
        'system_matches' => 'সিস্টেম ম্যাচসমূহ',
        'pending_verification' => 'যাচাইকরণের অপেক্ষায়',
        'success_rate' => 'সাফল্যের হার',
        'item_type_dist' => 'জিনিসের ধরনের বিন্যাস',
        'item_status_dist' => 'জিনিসের স্ট্যাটাসের বিন্যাস',
        'claim_status_dist' => 'দাবির স্ট্যাটাস',
        'category_dist' => 'ক্যাটাগরি বিন্যাস',
        'recent_activity' => 'সাম্প্রতিক কার্যকলাপ',
        
        'manage_users' => 'ব্যবহারকারী পরিচালনা',
        'manage_users_desc' => 'নিবন্ধিত সব ব্যবহারকারী দেখুন এবং পরিচালনা করুন',
        'all_users' => 'সকল ব্যবহারকারী',
        'joined_on' => 'যোগদানের তারিখ:',
        
        'manage_items' => 'জিনিসপত্র পরিচালনা',
        'manage_items_desc' => 'রিপোর্ট করা সমস্ত জিনিসপত্র দেখুন এবং পরিচালনা করুন',
        'all_items' => 'সকল জিনিসপত্র',
        
        'manage_claims' => 'দাবি পরিচালনা',
        'manage_claims_desc' => 'সমস্ত জিনিসের দাবির অনুরোধ পর্যালোচনা এবং প্রক্রিয়া করুন',
        'all_statuses' => 'সকল স্ট্যাটাস',
        'accepted' => 'গৃহীত',
        'rejected' => 'প্রত্যাখ্যাত',
        'all_claims' => 'সকল দাবি',
        'claimed_by' => 'দাবি করেছেন',
        'item_owner' => 'জিনিসের মালিক',
        
        'verify_matches' => 'সিস্টেম ম্যাচ যাচাই করুন',
        'verify_matches_desc' => 'স্মার্ট অ্যালগরিদম দ্বারা তৈরি হওয়া উচ্চ-সম্ভাব্য ম্যাচগুলি পর্যালোচনা করুন',
        'match_heuristics' => 'ম্যাচ হিউরিস্টিকস:',
        'no_pending_matches' => 'যাচাই করার জন্য কোনো পেন্ডিং সিস্টেম ম্যাচ নেই।',
        
        'admin_security' => 'অ্যাডমিন নিরাপত্তা',
        'admin_security_desc' => 'আপনার অ্যাডমিন অ্যাকাউন্টের জন্য একটি শক্তিশালী এবং অনন্য পাসওয়ার্ড ব্যবহার করুন',
    ]
];
